version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      python manage.py migrate
      python manage.py runserver 0.0.0.0:8040
    container_name: django_vision
    env_file:
      - .env
    restart: always
    environment:
      - DATABASE_URL
    volumes:
      - .:/code
    ports:
      - "8040:8040"
    depends_on:
      - db
